from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QLineEdit,
                               QMainWindow, QMenuBar, QPushButton, QSizePolicy,
                               QSlider, QStatusBar, QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(2000, 1100)
        MainWindow.setMinimumSize(QSize(2000, 1000))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(75, 171, 23, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(113, 255, 36, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(94, 213, 29, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(37, 85, 12, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(50, 114, 15, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush7 = QBrush(QColor(165, 213, 139, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush10 = QBrush(QColor(240, 240, 240, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        brush11 = QBrush(QColor(227, 227, 227, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush11)
        brush12 = QBrush(QColor(160, 160, 160, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush12)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        brush13 = QBrush(QColor(105, 105, 105, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush13)
        brush14 = QBrush(QColor(245, 245, 245, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush15 = QBrush(QColor(0, 0, 0, 128))
        brush15.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMouseTracking(True)
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.callButton = QPushButton(self.centralwidget)
        self.callButton.setObjectName(u"callButton")

        self.gridLayout.addWidget(self.callButton, 5, 2, 1, 1)

        self.passButton = QPushButton(self.centralwidget)
        self.passButton.setObjectName(u"passButton")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.passButton.sizePolicy().hasHeightForWidth())
        self.passButton.setSizePolicy(sizePolicy)
        self.passButton.setMinimumSize(QSize(150, 40))
        self.passButton.setMaximumSize(QSize(150, 40))

        self.gridLayout.addWidget(self.passButton, 6, 2, 1, 1)

        self.dealButton = QPushButton(self.centralwidget)
        self.dealButton.setObjectName(u"dealButton")
        sizePolicy.setHeightForWidth(
            self.dealButton.sizePolicy().hasHeightForWidth())
        self.dealButton.setSizePolicy(sizePolicy)
        self.dealButton.setMinimumSize(QSize(150, 40))
        self.dealButton.setMaximumSize(QSize(150, 40))

        self.gridLayout.addWidget(self.dealButton, 6, 1, 1, 1)

        self.raiseBetSlider = QSlider(self.centralwidget)
        self.raiseBetSlider.setObjectName(u"raiseBetSlider")
        sizePolicy.setHeightForWidth(
            self.raiseBetSlider.sizePolicy().hasHeightForWidth())
        self.raiseBetSlider.setSizePolicy(sizePolicy)
        self.raiseBetSlider.setMinimumSize(QSize(20, 400))
        self.raiseBetSlider.setMaximumSize(QSize(45, 405))
        self.raiseBetSlider.setBaseSize(QSize(20, 400))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush16 = QBrush(QColor(73, 156, 54, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush16)
        brush17 = QBrush(QColor(110, 234, 81, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush17)
        brush18 = QBrush(QColor(91, 195, 67, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush18)
        brush19 = QBrush(QColor(37, 78, 27, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush19)
        brush20 = QBrush(QColor(49, 104, 36, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush20)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush16)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush21 = QBrush(QColor(164, 205, 154, 255))
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush21)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush13)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush19)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush17)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush18)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush19)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush20)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush19)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush19)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
        self.raiseBetSlider.setPalette(palette1)
        self.raiseBetSlider.setCursor(QCursor(Qt.UpArrowCursor))
        self.raiseBetSlider.setFocusPolicy(Qt.ClickFocus)
        self.raiseBetSlider.setAutoFillBackground(False)
        self.raiseBetSlider.setOrientation(Qt.Vertical)
        self.raiseBetSlider.setTickPosition(QSlider.TicksBothSides)
        self.raiseBetSlider.setTickInterval(5)

        self.raiseBetSlider.valueChanged.connect(self.valueChanged)
        self.gridLayout.addWidget(self.raiseBetSlider, 4, 3, 1, 1)

        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(250, 10))
        self.label.setMaximumSize(QSize(750, 50))
        font1 = QFont()
        font1.setPointSize(20)
        self.label.setFont(font1)

        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.raiseButton = QPushButton(self.centralwidget)
        self.raiseButton.setObjectName(u"raiseButton")
        self.raiseButton.setMaximumSize(QSize(150, 40))

        self.gridLayout.addWidget(self.raiseButton, 6, 3, 1, 1)

        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        sizePolicy.setHeightForWidth(
            self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QSize(10, 20))
        self.lineEdit.setMaximumSize(QSize(50, 40))
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setMaxLength(2)
        self.lineEdit.setEchoMode(QLineEdit.Password)
        self.lineEdit.setAlignment(
            Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)

        self.gridLayout.addWidget(self.lineEdit, 3, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 2000, 38))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(
            QCoreApplication.translate("MainWindow", u"My Awesome Poker App",
                                       None))
        self.callButton.setText(
            QCoreApplication.translate("MainWindow", u"Call", None))
        self.passButton.setText(
            QCoreApplication.translate("MainWindow", u"Pass", None))
        self.dealButton.setText(
            QCoreApplication.translate("MainWindow", u"Deal", None))
        self.raiseBetSlider.setToolTip("")
        self.raiseBetSlider.setStatusTip("")
        self.label.setText(QCoreApplication.translate("MainWindow",
                                                      u"Enter the amount of hands would you like to play at a time?",
                                                      None))
        self.raiseButton.setText(
            QCoreApplication.translate("MainWindow", u"Raise", None))
        self.lineEdit.setInputMask(
            QCoreApplication.translate("MainWindow", u"0.", None))
        self.lineEdit.setPlaceholderText(
            QCoreApplication.translate("MainWindow", u"2", None))
    def valueChanged(self, v):
        print(v)
